server:
  port: 8082
spring:
  application:
    # 服务之间调用一般都是根据此 name
    name: eureka-client
eureka:
  client:
    service-url:
      # eureka 服务器发布地址
      defaultZone: http://localhost:8080/eureka/